name: skykatana-gpu
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numba
  - cupy
  - "cuda-version=12.6"
  - "cuda-nvrtc=12.6"
  - "cuda-nvcc=12.6"
  - "cuda-cudart=12.6"
  - pip
  - matplotlib
  - jupyterlab
