site_name: Skykatana

nav:
  - Introduction: index.md
  - Installation: install.md
  - Example 1 - Masks for HSC: quick_example_hsc.md
  - Example 2 - Masks for Rubin: quick_example_rubin.md
  - Example 3 - Funny masks: bonus_example.md
  - Healsparse map basics: hspbasic.md
  - HATS & LSDB basics: hatsbasic.md
  - Creating footmasks: creating_footmaps.md
  - IO format: io.md
  - API: api.md

theme:
  name: material
  logo: images/logo.png
  favicon: images/sword-cross-custom.png
  palette:
    scheme: slate
    primary: blue grey
    accent: yellow
  font:
    text: Merriweather Sans
    code: Red Hat Mono

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src      # <<— no tabs; pure spaces
          options:
            show_root_heading: true
            docstring_style: numpy
            docstring_section_style: table
            summary: true
            group_by_category: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            modernize_annotations: true

extra_css:
  - css/mkdocstrings.css
  - css/typography.css
  - css/overrides.css
  - css/notebook-styles.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - attr_list
  - md_in_html

# This 'extra' key is optional and not used by Material; safe to remove.
# extra:
#   python_path: "src"
